// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace test {

static const char* Greeting_method_names[] = {
  "/test.Greeting/SayHello",
};

std::unique_ptr< Greeting::Stub> Greeting::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeting::Stub> stub(new Greeting::Stub(channel));
  return stub;
}

Greeting::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(Greeting_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeting::Stub::SayHello(::grpc::ClientContext* context, const ::test::HelloRequest& request, ::test::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeting::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::test::HelloRequest* request, ::test::HelloReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::test::HelloReply>* Greeting::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::test::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::test::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::test::HelloReply>* Greeting::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::test::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::test::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false);
}

Greeting::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeting_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeting::Service, ::test::HelloRequest, ::test::HelloReply>(
          std::mem_fn(&Greeting::Service::SayHello), this)));
}

Greeting::Service::~Service() {
}

::grpc::Status Greeting::Service::SayHello(::grpc::ServerContext* context, const ::test::HelloRequest* request, ::test::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

